sudo: false

language: c

matrix:
  include:
    - env: FLAGS="" ARGS=""
      compiler: ": #stack default"
      addons: {apt: {packages: [libgmp-dev]}}
    - env: FLAGS="" ARGS="--stack-yaml=stack-previous.yaml"
      compiler: ": #stack previous"
      addons: {apt: {packages: [libgmp-dev]}}

before_install:
- unset CC
- mkdir -p $HOME/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- stack $ARGS --no-terminal setup
- stack $ARGS --no-terminal install hlint

script:
- hlint .
- stack $ARGS --no-terminal test $FLAGS --haddock
- stack $ARGS --no-terminal bench $FLAGS

cache:
  directories:
  - $HOME/.stack
