name:       csg
version:    "0.1"
synopsis:   Analytical CSG (Constructive Solid Geometry) library
github:     dzhus/csg
license:    BSD3
author:     Dmitry Dzhus
maintainer: dima@dzhus.org
category:   Graphics

extra-source-files:
  - CHANGELOG.md
  - README.md

ghc-options:
  - -Wall
  - -Wcompat
  - -O2

dependencies:
  - base < 5
  - simple-vec3 >= 0.3.1
  - strict

library:
  source-dirs: src
  other-modules:
    - Data.CSG.Util
  dependencies:
    - attoparsec
    - bytestring
    - containers
    - transformers

benchmarks:
  csg-benchmark:
    main: benchmark/Benchmark.hs
    dependencies:
      - criterion
      - csg
      - vector

executables:
  csg-raycaster:
    source-dirs: exe
    main: raycaster.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - '"-with-rtsopts=-N"'
    dependencies:
      - csg
      - gloss
      - gloss-raster
      - system-filepath
      - turtle
