name:       csg
version:    "0.1"
synopsis:   Analytical CSG (Constructive Solid Geometry) library
github:     dzhus/csg
license:    BSD3
author:     Dmitry Dzhus
maintainer: dima@dzhus.org
category:   Graphics

extra-source-files:
  - CHANGELOG.md
  - README.md
  - examples/cube.geo
  - examples/reentry.geo

ghc-options:
  - -Wall
  - -Wcompat
  - -O2

dependencies:
  - base < 5
  - simple-vec3 >= 0.4

library:
  source-dirs: src
  dependencies:
    - attoparsec
    - bytestring
    - containers
    - strict
    - QuickCheck
    - transformers

  when:
    - condition: flag(triples)
      cpp-options: -DWITH_TRIPLES

benchmarks:
  csg-benchmark:
    main: benchmark/Benchmark.hs
    dependencies:
      - criterion
      - csg
      - strict
      - vector

tests:
  csg-tests:
    source-dirs: tests
    main: Main.hs
    dependencies:
      - bytestring
      - csg
      - tasty
      - tasty-hunit
      - tasty-quickcheck

  csg-doctests:
    source-dirs: tests
    main: doctest-driver.hs
    ghc-options: -threaded
    dependencies:
      - doctest
      - doctest-discover >= 0.1.0.8

executables:
  csg-raycaster:
    source-dirs: exe
    main: raycaster.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - '"-with-rtsopts=-N"'
    dependencies:
      - csg
      - gloss
      - gloss-raster
      - system-filepath
      - QuickCheck
      - strict
      - turtle

flags:
  triples:
    description: Use triples of Doubles to represent vectors
                 (slower with vector library arrays)
    manual: true
    default: false
