name:       csg
version:    "0.1"
synopsis:   Analytical CSG (Constructive Solid Geometry) library
github:     dzhus/csg
license:    BSD3
author:     Dmitry Dzhus
maintainer: dima@dzhus.org
category:   Graphics

extra-source-files:
  - CHANGELOG.md
  - README.md

ghc-options:
  - -Wall
  - -Wcompat
  - -O2

dependencies:
  - base < 5
  - simple-vec3 >= 0.3.1

library:
  source-dirs: src
  dependencies:
    - attoparsec
    - bytestring
    - containers
    - strict
    - QuickCheck
    - transformers

benchmarks:
  csg-benchmark:
    main: benchmark/Benchmark.hs
    dependencies:
      - criterion
      - csg
      - strict
      - vector

tests:
  csg-tests:
    source-dirs: tests
    main: Main.hs
    dependencies:
      - bytestring
      - csg
      - tasty
      - tasty-hunit
      - tasty-quickcheck

executables:
  csg-raycaster:
    source-dirs: exe
    main: raycaster.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - '"-with-rtsopts=-N"'
    dependencies:
      - csg
      - gloss
      - gloss-raster
      - system-filepath
      - QuickCheck
      - strict
      - turtle
